export default {
    light_gray          : '#B5B5B5',
    bold_gray           : '#959595',
    black               : '#2C2C2C',
    wight               : '#fafafa',
    dash                : '#DDD',
    purple              : '#000203',
    orange              : '#F99F2F',
    red                 : '#EF3434',
    green               : '#006633',
    light_green         : '#9BB200',
    yellow              : '#FFF700',
    toby                : '#c37b6a',
    turquoise           : '#3ABDC4',
}
